[package]
name = "variables"
version = "2.3.4"
edition = "2021"
authors = ["Brian Lynnerup Pedersen <brian.lynnerup.pedersen@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
